tellor-io/tellor-pallet

runtime-api/src/lib.rs
src/tests/oracle.rs

Recent call confirmed these functions as not required for the pallet.

chore: remove irrelevant functions

---

.github/workflows/check.yml
.github/workflows/test.yml
README.md

Updates the GH workflows to use the `main` branch, along with badges within readme.

ci: update to main branch

---

runtime-api/src/tests.rs
src/constants.rs
src/impls.rs
src/lib.rs
src/mock.rs
src/tests/autopay.rs
src/tests/governance.rs
src/tests/mod.rs
src/tests/oracle.rs
src/traits.rs
src/types.rs

- Replaces `Time` trait usage with `UnixTime` for more explicit timestamp values (`u64`)
- Uses seconds via `now()` function to align `timestamp` values with EVM smart contract timestamps
- Converts time period configuration items to constants
- Converts `Hasher` config item to use `keccak256` hashing algorithm exclusively via type alias

fix: convert non-configurable items

---

src/impls.rs
src/traits.rs

Allows pallet consumers to get current timestamp in seconds.
Closes #30

feat: expose now() via usingtellor trait

---

runtime-api/src/autopay.rs
runtime-api/src/governance.rs
runtime-api/src/lib.rs
runtime-api/src/tests.rs
src/contracts/mod.rs
src/impls.rs
src/lib.rs
src/mock.rs
src/tests/governance.rs
src/tests/mod.rs
src/tests/oracle.rs
src/types.rs

Proposed changes to standardise on `dispute_id` as hash as per parachain contracts, with incrementing vote rounds per `dispute_id`.

refactor: standardise on dispute_id hash

---

src/contracts/registry.rs
src/lib.rs
src/tests/mod.rs

Closes #26 
**NOTE:** should only be merged once the parameter has been removed from the corresponding `register` function in the `ParachainRegistry` contract. See https://github.com/tellor-io/tellor-parachain-contracts/issues/17 for more info.

fix: remove unnecessary stake_amount parameter from register contract call encoding

---

src/impls.rs
src/lib.rs
src/tests/governance.rs
src/tests/oracle.rs
src/types.rs

- removes `vote_round` parameter from `execute_vote(..)`, as the final (current) round is always used once vote executed
- realigns implementation with `executeVote` implementation in source contract
- removes the `VoteNotFinal` error variant as no longer required. Previously a `dispute_id` was an integer and needed to be checked to ensure it was the final round. Now that it is a hash, we use the `VoteRound::get(dispute_id)` value to get the current (final) round.
- merges the `report_invalid_dispute` & `slash_dispute_initiator` functions into a single `report_vote_executed` dispatchable function
- removes `dispute_id` from `report_slash`, as this is called at time of first dispute rather than at time of vote execution. also removes call to `execute_vote` as handled later by contracts.
- …

`execute_vote` improvements

---

runtime-api/src/autopay.rs
runtime-api/src/lib.rs
runtime-api/src/tests.rs
src/impls.rs
src/lib.rs
src/mock.rs
src/tests/autopay.rs
src/tests/governance.rs
src/tests/mod.rs
src/tests/oracle.rs
src/types.rs

Separates stake `Amount` (TRB as reported from controller chain) from `Balance` (native parachain currency used for onetime tips, funding feeds, accumulate rewards and dispute fees).
`U256` used for stake amount due to usage in controller contracts and that reporters can overstake, theoretically exceeding `u128`.
Adds a simple `convert()` function for converting from a stake amount into a local balance, which will be replaced with functionality which performs the conversion based on oracle value.

Separate stake from balance

---

runtime-api/src/tests.rs
src/constants.rs
src/impls.rs
src/lib.rs
src/tests/autopay.rs
src/tests/mod.rs

Simplifies pallet sub-account usage and naming makes logic much easier to follow.

refactor: relocate sub-account lookups into helper functions

---

runtime-api/src/governance.rs
runtime-api/src/lib.rs
runtime-api/src/tests.rs
src/constants.rs
src/contracts/governance.rs
src/contracts/mod.rs
src/contracts/staking.rs
src/impls.rs
src/lib.rs
src/mock.rs
src/tests/governance.rs
src/tests/mod.rs
src/tests/oracle.rs
src/types.rs

Ports staking rewards functionality from `tellorFlex`, where staking rewards are accumulated/paid using the (native) token configured by the parachain and based on ratio of staked TRB amount. All fees/rewards therefore use the `BalanceOf<T>` type, versus any stake amount from the controller chain which uses the `Tributes` (`U256`) type, attempting to maintain a clear distinction between the two.
The general approach followed throughout is to call the `convert()` function to convert a stake amount (`Tributes`) into a local equivalent amount of tokens (`Balance`) and then follow any existing logic from `tellorFlex` to calculate the applicable rates and rewards.
A summary of changes:
- adds `DECIMALS` constant, set to 18 for TRB decimals
- introduces `Decimals: Get<u8>` config item for …

Add staking rewards

---

runtime-api/src/tests.rs
src/impls.rs
src/lib.rs
src/mock.rs
src/tests/autopay.rs
src/tests/governance.rs
src/tests/mod.rs
src/tests/oracle.rs

- adds `MinimumStakeAmount` config item, which is used by `StakeAmount<T>` storage item until value set
- adds `StakeAmountCurrencyTarget` config item, for setting stake amount target in some currency (e.g. USD 1,500)
- adds `StakingTokenPriceQueryId` config item, for obtaining rate for converting between TRB and currency from oracle
- adds `UpdateStakeAmountInterval` config item, for configuring how frequently the stake amount is updated via hook
- hook compares current time vs `LastStakeAmountUpdate<T>  + interval`, where interval is configured interval or some minimum interval
- adds `update_stake_amount` dispatchable function, updating the stake amount based on oracle price and stake amount currency target
- removes `stake_amount` from `register` dispatchable function as no longer …

Improve min stake amount

---

src/impls.rs
src/lib.rs
src/tests/governance.rs
src/tests/oracle.rs

- adds `report_vote_tallied` dispatchable function, taking `dispute_id` and `result` and calling internal `tally_votes` function
- ensures the vote has not already been executed when tallying
- adds missing `result` to `VoteTallied` event
- adds check to `begin_dispute` ensure that previous round has not been executed when starting a new round
- removes `result` parameter from `report_vote_executed` dispatchable function and internal `execute_vote` function, as result set on vote within tally call
- safe math
- updates tests accordingly
Closes #53

fix: report vote tallied

---

runtime-api/src/tests.rs
src/lib.rs
src/mock.rs
src/tests/autopay.rs
src/tests/governance.rs
src/tests/mod.rs
src/tests/oracle.rs
src/xcm/mod.rs

Separates the configuration of fees used for cross-chain transact from the registration of the parachain with registry controller contract, as the current implementation mixes concerns.
- adds a `ConfigureOrigin` to config to allow parachain to specify who can call `configure()`, separate to the `RegisterOrigin` for the the `register`/`deregister` calls.
- renames `xcm::transact_with_config()` function to `xcm::transact()` as overload no longer required.
Closes #47

fix: separate configure from register

---

runtime-api/src/tests.rs
src/constants.rs
src/lib.rs

Ensures certain constants are publicly available for usage within runtime config.

fix: expose time periods

---

src/lib.rs

- uses `Identity` hasher for: 
- `dispute_id` as hashed internally using `Keccak256`, with only 1/3 hash inputs controlled by caller (`query_id`)
- `query_id` as it is either verified by `Keccak256`hashing corresponding `query_data` parameter or by checking against existing state (which in turn was verified).
- `feed_id` as created by `keccak256` hashing data including `query_id`, which in turn is a `keccak256` hash. Other accesses first verify `feed_id` exists before mutating.
- uses `TwoX` hasher for `vote_round` as not directly controlled by caller and requires increasing dispute fee to be paid for each round
**Note:** A careful review is required, along with consideration of the effects of these optimisations, so please take your time with this one. More information at …

refactor: optimise storage hashers

---

runtime-api/src/lib.rs
runtime-api/src/tests.rs
src/impls.rs
src/lib.rs
src/mock.rs
src/tests/autopay.rs
src/tests/governance.rs
src/tests/mod.rs
src/tests/oracle.rs

`pallet`
- adds `InitialDisputeFee` and `StakingToLocalTokenPriceQueryId` config items for defining initial dispute fee as well as `query_id` for ongoing updates of dispute fee, based on TRB:OCP token price
- adds `calculate_dispute_fee()` function to calculate dispute fee based on stake amount and supplied price
- adds `update_dispute_fee()` for updating the `DisputeFee` storage item with latest value based on orcle price.
- only persists and emits `NewDisputeFee` event if value has actually changed
- updates `update_stake_amount` and `on_initialize` hook to update dispute fee along with stake amount, ensuring both complete successfully for state to be updated.
- hook uses storage transaction to ensure stake amount and dispute fee updated together
- adds/updates tests to ensure that …

feat: convert dispute fee to local balance using oracle

---

Cargo.toml
src/contracts/governance.rs
src/contracts/mod.rs
src/contracts/registry.rs
src/contracts/staking.rs
src/lib.rs

The existing abi encoding requirements were rather basic so I simply mirrored some of the functionality of [ethabi](https://github.com/rust-ethereum/ethabi) to not have to take a non-dev dependency and then verified the simple implementation using the same crate via tests. It seems like to we need to do some slightly more advanced encoding now, so it is probably a good opportunity to replace the simple encoding with something more robust, eliminating a lot of redundant code.
Please can you review the library and ensure that you are happy to take on this dependency before approving. The crate was historically created by Parity I believe, before being turned over to the community. https://github.com/rust-ethereum/ethabi/network/dependents shows the projects dependent on the crate and there …

build: use ethabi

---

runtime-api/src/tests.rs
src/impls.rs
src/lib.rs
src/mock.rs

Better aligns with the descriptions of the `Inspect` and `Transfer` traits used as bounds for the `Asset` config item, namely 'fungible asset'.

refactor: rename token to asset

---

src/contracts/mod.rs
src/contracts/registry.rs
src/contracts/staking.rs
src/impls.rs
src/lib.rs
src/mock.rs
src/tests/governance.rs
src/tests/mod.rs
src/types.rs

Sends any pending votes which are due to the governance contract for tallying via:
- `send_vote` dispatchable function, callable by anyone and allowing a max number of votes to be sent
- `on_initialize()` hook, checking for any pending votes to be sent on _every_ block
Votes are added to the queue (`PendingVotes` storage item) for each dispute round, scheduled to be sent after `11 hours` have passed. An additional check on the `vote(`) function only allows users/reporters to vote until the vote has been sent.
Note: The implementation will only send pending votes which have become due based on scheduled timestamp and only send some maximum number per invocation. Votes are removed from the 'queue' once successfully sent. The `Vote::sent` flag is set and a `VoteSent` event is emitted.

feat: send votes to governance contract

---

runtime-api/src/tests.rs
src/contracts/mod.rs
src/impls.rs
src/lib.rs
src/mock.rs
src/tests/autopay.rs
src/traits.rs
src/types.rs

- removes `Price` and `ValueConverter` config items as price is always `U256` (18 decimals) according to data specs
- `BytesToU256` converter handles conversion, returning `Some(U256)` when provided input vector is expected length otherwise `None`
Closes #70 , #20.

refactor: improve value to price conversion

---

Cargo.toml
runtime-api/src/tests.rs
src/contracts/mod.rs
src/contracts/registry.rs
src/lib.rs
src/mock.rs
src/tests/mod.rs
src/xcm/mod.rs

Based on @pawanbisht62's work and companion to https://github.com/tellor-io/tellor-parachain-contracts/pull/59:
- adds two new config items which allows parachain to configure the `FeeLocation` and `WeightToFee` used when registering the parachain with the contracts. These values are used to calculate the fees (amount and type) to be withdrawn to pay for execution of the call to the pallet on the consumer parachain
- adds `FeeLocation<T> `helper type for converting from config to `MultiLocation`
- encodes the `Junctions` within the `MultiLocation` used to denote the fee_location using Moonbeam's Solidity precompile encoding scheme
- adds weights to the various dispatchable functions, which are then used in the contracts to calculate the weight/fee required
- increases the `REGISTER` gas …

feat: add custom weight and update registration

---

src/impls.rs
src/lib.rs
src/tests/oracle.rs

Replaces `saturating_`* with `checked_`* for more explicit safe math handling.
This PR uncovered an overflow in price change conversion within `get_reward_amount()` due to `price_change` being a `u16` (to match `feed.details.price_threshold`) and the test values causing the result to exceed this type. The overflow occurred when switching from `saturated_into()` to `checked_into()` on the resulting price change calculation result. 
@oraclown are you happy for the maximum price change percentage to saturate into a max `u16` value (`65_535`)?

fix: safe math

---

src/lib.rs

Updates `begin_dispute()` to only write `Dispute` to `DisputeInfo` storage on the first vote round, as corresponding struct values dont change thereafter. 
Current implementation writes same values on each subsequent vote round for same `query_id` and `timestamp`. This logic is left over from when `dispute_id` was an incrementing integer instead of a `hash(para_id, query_id, timestamp)`.
Closes #81

refactor: only write dispute info on first vote round

---

runtime-api/src/tests.rs
src/impls.rs
src/lib.rs
src/mock.rs
src/tests/governance.rs

- moves `vote()` implementation to `do_vote()`
- adds `vote_on_multiple_disputes()` dispatchable function, which iterates over bounded votes parameter, calling `do_vote()` for each
- adds `MaxDisputeVotes` config item, for configuring the maximum number of disputes which can be voted on in a single call
- adds vote_on_multiple_disputes() test implementation from source contract tests
Closes #79

feat: vote on multiple disputes

---

src/impls.rs

Simple fix to limits batch of timestamps processed to 100. Could be made configurable in the future if ever required.
Closes #80

fix: bound timestamps in reward getters

---

runtime-api/src/lib.rs
src/lib.rs
src/tests/oracle.rs

Simply removes the 'todo' flags from time-based rewards functionality and labels as 'backlog'. Could alternatively remove completely.
See #11 for more information

docs: flag time-based rewards functionality as a backlog item

---

src/impls.rs
src/lib.rs
src/mock.rs
src/tests/governance.rs
src/tests/mod.rs
src/tests/oracle.rs
src/xcm/mod.rs

- adds `event` parameter to `send_xcm`() helper function, ensuring that all xcm sent emits an event once successful
- updates all corresponding events to end with _Sent_
- adds missing event assertions to tests
- uses `assert_has_event` rather than `assert_last_event` for second to last event
Closes #82

feat: emit events once xcm sent

---

src/lib.rs

Copies a dummy missing weight until benchmarks complete.

refactor: remove dev_mode

---

src/lib.rs
src/mock.rs
src/tests/governance.rs

Fixes calculation of dispute fee to saturate into `Balance` type. 
**Note:** even if calculated dispute fee saturates, it is still set to a maximum of the stake amount. 
- updates `begin_dispute` to use `saturating_*` math when calculating dispute fee 
- also corrects stake amount to be calculated as dispute fee * 10, to account for variability of dispute fee in local token in relation to 10% of 100 TRB
- adds `begin_dispute_fee_saturates` and `begin_dispute_round_fee_saturates` tests which ensure at least up to 256 rounds/opens disputes supported
- sets `MaxTimestamps` config value in mock runtime, effectively constraining number of reports per query_id to a max of 100 years

fix: saturate dispute fees

---

src/lib.rs

Some users will push data to oracle and don't care if someone else is submitting at the same time.

docs: remove comment

---

runtime-api/src/tests.rs
src/lib.rs
src/mock.rs

Simple change to improve the name of a config item. It was previously named this way due to MaxVotes already being used for something else, recently removed via storage optimisations.

refactor: improve config item name

---

src/lib.rs
src/mock.rs
src/tests/autopay.rs

Annotates any unsigned integer (`u32` and above) as compact encoded. More information at https://substrate.stackexchange.com/a/686/3138.
Note: additional optimisations can be done on the storage items themselves, such as all the timestamps in the `Report*` storage items.

feat: compact encoding

---

src/contracts/registry.rs
src/lib.rs
src/tests/mod.rs
src/types.rs

This PR pertains to send extrinsics weights to parachain contract as each parachain will have different weights based on their pallet configuration.
Resolves: https://github.com/tellor-io/tellor-pallet/issues/90
Depends on https://github.com/tellor-io/tellor-pallet/pull/94.
This is the fresh PR for sending extrinsic weights in registration flow in order to avoid any commit confusions. For context here is the previous [PR](https://github.com/tellor-io/tellor-pallet/pull/96).

Send extrinsic weights in registration

---

runtime-api/src/lib.rs
runtime-api/src/tests.rs
src/impls.rs
src/lib.rs
src/mock.rs
src/tests/autopay.rs
src/types.rs

- refactors `FeedsWithFunding`, `QueryIdsWithFunding` and `Tips` storage items to use maps, eliminating the need to track array indices
- adds `TipCount` storage item
- removes `QueryIdsWithFundingIndex` storage item as no longer required
- removes `Feed.feeds_with_funding_index` as no longer required
- removes `MaxFundedFeeds` and `MaxTipsPerQuery` config items as no longer necessary
- removes `MaxFeedsFunded` and `MaxTipsReached` error variants no longer used

refactor: optimise storage

---

src/benchmarking.rs
src/lib.rs
src/tests/governance.rs
src/tests/oracle.rs

Parachain governance contract calls staking contract ([ref](https://github.com/tellor-io/tellor-parachain-contracts/blob/f693960b6709a84a372b8bb34abf3afbe1a03404/src/ParachainGovernance.sol#L168)) to slash reporter on dispute , resulting in the originating address of the `report_slash` call ([ref](https://github.com/tellor-io/tellor-parachain-contracts/blob/f693960b6709a84a372b8bb34abf3afbe1a03404/src/ParachainStaking.sol#L264)) being the staking contract rather than governance.

fix: use staking origin for report_slash

---

src/lib.rs
src/tests/oracle.rs

Adds a simple event to `add_staking_rewards`, inline with all the other dispatchables.
Note: this only adds it to the main dispatchable function and not all usages of the inner `do_add_staking_rewards` function, typically called when claiming tips.

fix: add missing event

---

src/lib.rs
src/tests/governance.rs

`reporter` should be the disputed reporter and not the reporter of the dispute.

fix: correct reporter on newdispute event

---

runtime-api/src/tests.rs
src/impls.rs
src/lib.rs
src/mock.rs
src/tests/governance.rs
src/tests/mod.rs
src/xcm/ethereum_xcm.rs

Externalizes the pallet index of the Ethereum-Xcm pallet in the destination chain runtime, so that the pallet can easily be configured for use with different runtimes/networks (e.g. Moonbase has the pallet configured at index 38 whereas Moonbeam/Moonriver have it at 109).
Also enables usage with any other evm parachain which adds the ethereum-xcm pallet to their runtime in the future.
Closes #115

fix: externalize config of ethereum-xcm pallet index on destination chain

---

src/benchmarking.rs
src/constants.rs
src/lib.rs
src/tests/governance.rs
src/tests/mod.rs
src/tests/weights.rs

Required as xcm_transactor transact calls from evm parachain have a static `weight.proof_size` limit ([ref](https://github.com/PureStake/moonbeam/blob/ebb50badabea6021e3f593b19eecd3d84805ce49/precompiles/xcm-transactor/src/functions.rs#L355)), requiring the max `weight.proof_size` of `report_vote_executed` to function within that limit.
https://github.com/PureStake/moonbeam/blob/ebb50badabea6021e3f593b19eecd3d84805ce49/precompiles/xcm-transactor/src/functions.rs#L171 also implies that this may change in the future.
Adds checks for this in the `tests/weights/verify` test.

fix: further limit max vote rounds

---

src/lib.rs
src/tests/autopay.rs
src/tests/governance.rs
src/tests/mod.rs
src/tests/using_tellor.rs

Uses corresponding parameter values in pre-dispatch weight calculation when possible. Includes weight info when an error occurs for weight refund (only for weight functions with complexity parameter).
Closes #127

fix: optimise weights

---

src/benchmarking.rs
src/contracts/mod.rs
src/lib.rs
src/tests/governance.rs
src/tests/mod.rs
src/xcm/mod.rs

Allows permissioned caller to optionally override the gas limit used when calling the registry contract, should the gas amount required on the destination chain increase beyond the pallet default.

feat: allow optional gas limit when registering
